version: '3.8'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: exoplanet
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_USERNAME: ${MONGO_USER}
      MONGO_INITDB_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./data/mongo:/data/db
      - ./data/mongo-init/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    ports:
      - "27017:27017"
  api:
    build:
      context: ./
      dockerfile: api.dockerfile
    volumes:
      - './api:/app'
    ports:
      - "8000:8000"
    environment:
      MONGODB_USER: ${MONGO_USER}
      MONGODB_PASSWORD: ${MONGO_PASSWORD}
      PYTHONPATH: /app
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    ports:
      - "8888:80"
    environment:
      VITE_API_URL: http://0.0.0.0:8000
