export { default as About } from './About'
export { default as Home } from './Home'
export { default as Benchmark } from './Benchmark'
export { default as Fitting } from './Fitting'
export { default as NotFound } from './NotFound'
